export type Vehicle = {
  id: string;
  stockNo: string;
  vin: string;
  year: number;
  make: string;
  model: string;
  trim: string;
  condition: "new" | "used";
  msrp: number;
  invoice: number | null;
  sellingPrice: number;
  daysOnLot: number;
  status: "available" | "sold" | "in-transit" | "hold";
  exteriorColor: string;
  interiorColor: string;
  mileage: number;
  imageUrl: string;
};

export const inventory: Vehicle[] = [
  // --- New 2026 Honda CR-V ---
  {
    id: "veh-1",
    stockNo: "H1001",
    vin: "2HKRW2H53RH400101",
    year: 2026,
    make: "Honda",
    model: "CR-V",
    trim: "EX-L",
    condition: "new",
    msrp: 38400,
    invoice: 35900,
    sellingPrice: 38400,
    daysOnLot: 12,
    status: "available",
    exteriorColor: "Radiant Red Metallic",
    interiorColor: "Black Leather",
    mileage: 0,
    imageUrl: "",
  },
  {
    id: "veh-2",
    stockNo: "H1002",
    vin: "2HKRW2H55RH400102",
    year: 2026,
    make: "Honda",
    model: "CR-V",
    trim: "Sport",
    condition: "new",
    msrp: 35850,
    invoice: 33500,
    sellingPrice: 35850,
    daysOnLot: 8,
    status: "available",
    exteriorColor: "Lunar Silver Metallic",
    interiorColor: "Gray Cloth",
    mileage: 0,
    imageUrl: "",
  },
  {
    id: "veh-3",
    stockNo: "H1003",
    vin: "2HKRW2H57RH400103",
    year: 2026,
    make: "Honda",
    model: "CR-V",
    trim: "Sport Touring Hybrid",
    condition: "new",
    msrp: 42750,
    invoice: 39800,
    sellingPrice: 42750,
    daysOnLot: 3,
    status: "available",
    exteriorColor: "Canyon River Blue Metallic",
    interiorColor: "Black Leather",
    mileage: 0,
    imageUrl: "",
  },
  // --- New 2026 Honda Civic ---
  {
    id: "veh-4",
    stockNo: "H1004",
    vin: "19XFL1H70RE200204",
    year: 2026,
    make: "Honda",
    model: "Civic",
    trim: "Sport",
    condition: "new",
    msrp: 29500,
    invoice: 27600,
    sellingPrice: 29500,
    daysOnLot: 18,
    status: "available",
    exteriorColor: "Rallye Red",
    interiorColor: "Black Cloth",
    mileage: 0,
    imageUrl: "",
  },
  {
    id: "veh-5",
    stockNo: "H1005",
    vin: "19XFL1H72RE200205",
    year: 2026,
    make: "Honda",
    model: "Civic",
    trim: "Touring",
    condition: "new",
    msrp: 32900,
    invoice: 30700,
    sellingPrice: 32900,
    daysOnLot: 22,
    status: "available",
    exteriorColor: "Meteorite Gray Metallic",
    interiorColor: "Black Leather",
    mileage: 0,
    imageUrl: "",
  },
  {
    id: "veh-6",
    stockNo: "H1006",
    vin: "19XFL1H74RE200206",
    year: 2025,
    make: "Honda",
    model: "Civic",
    trim: "EX",
    condition: "new",
    msrp: 30750,
    invoice: 28700,
    sellingPrice: 29999,
    daysOnLot: 45,
    status: "available",
    exteriorColor: "Platinum White Pearl",
    interiorColor: "Gray Cloth",
    mileage: 0,
    imageUrl: "",
  },
  // --- New 2026 Honda Accord ---
  {
    id: "veh-7",
    stockNo: "H1007",
    vin: "1HGCY2F50RA300307",
    year: 2026,
    make: "Honda",
    model: "Accord",
    trim: "Sport Hybrid",
    condition: "new",
    msrp: 36200,
    invoice: 33800,
    sellingPrice: 36200,
    daysOnLot: 5,
    status: "available",
    exteriorColor: "Still Night Pearl",
    interiorColor: "Black Cloth",
    mileage: 0,
    imageUrl: "",
  },
  {
    id: "veh-8",
    stockNo: "H1008",
    vin: "1HGCY2F52RA300308",
    year: 2026,
    make: "Honda",
    model: "Accord",
    trim: "Touring Hybrid",
    condition: "new",
    msrp: 40550,
    invoice: 37900,
    sellingPrice: 40550,
    daysOnLot: 2,
    status: "in-transit",
    exteriorColor: "Platinum White Pearl",
    interiorColor: "Ivory Leather",
    mileage: 0,
    imageUrl: "",
  },
  {
    id: "veh-9",
    stockNo: "H1009",
    vin: "1HGCY2F54RA300309",
    year: 2025,
    make: "Honda",
    model: "Accord",
    trim: "EX-L Hybrid",
    condition: "new",
    msrp: 37900,
    invoice: 35400,
    sellingPrice: 37250,
    daysOnLot: 38,
    status: "available",
    exteriorColor: "Meteorite Gray Metallic",
    interiorColor: "Black Leather",
    mileage: 0,
    imageUrl: "",
  },
  // --- New 2026 Honda HR-V ---
  {
    id: "veh-10",
    stockNo: "H1010",
    vin: "3CZRU6H31RM500410",
    year: 2026,
    make: "Honda",
    model: "HR-V",
    trim: "EX-L",
    condition: "new",
    msrp: 31450,
    invoice: 29400,
    sellingPrice: 31450,
    daysOnLot: 14,
    status: "available",
    exteriorColor: "Urban Gray Pearl",
    interiorColor: "Black Leather",
    mileage: 0,
    imageUrl: "",
  },
  {
    id: "veh-11",
    stockNo: "H1011",
    vin: "3CZRU6H33RM500411",
    year: 2026,
    make: "Honda",
    model: "HR-V",
    trim: "Sport",
    condition: "new",
    msrp: 29150,
    invoice: 27300,
    sellingPrice: 29150,
    daysOnLot: 9,
    status: "available",
    exteriorColor: "Nordic Forest Pearl",
    interiorColor: "Gray Cloth",
    mileage: 0,
    imageUrl: "",
  },
  // --- New 2026 Honda Pilot ---
  {
    id: "veh-12",
    stockNo: "H1012",
    vin: "5FNYF6H98RB600512",
    year: 2026,
    make: "Honda",
    model: "Pilot",
    trim: "Touring",
    condition: "new",
    msrp: 49350,
    invoice: 46100,
    sellingPrice: 49350,
    daysOnLot: 6,
    status: "available",
    exteriorColor: "Obsidian Blue Pearl",
    interiorColor: "Black Leather",
    mileage: 0,
    imageUrl: "",
  },
  {
    id: "veh-13",
    stockNo: "H1013",
    vin: "5FNYF6H90RB600513",
    year: 2026,
    make: "Honda",
    model: "Pilot",
    trim: "TrailSport",
    condition: "new",
    msrp: 47990,
    invoice: 44800,
    sellingPrice: 47990,
    daysOnLot: 11,
    status: "hold",
    exteriorColor: "Diffused Sky Blue Pearl",
    interiorColor: "Black/Orange Leather",
    mileage: 0,
    imageUrl: "",
  },
  {
    id: "veh-14",
    stockNo: "H1014",
    vin: "5FNYF6H92RB600514",
    year: 2025,
    make: "Honda",
    model: "Pilot",
    trim: "EX-L",
    condition: "new",
    msrp: 44350,
    invoice: 41400,
    sellingPrice: 43500,
    daysOnLot: 52,
    status: "available",
    exteriorColor: "Platinum White Pearl",
    interiorColor: "Gray Leather",
    mileage: 0,
    imageUrl: "",
  },
  // --- New 2026 Honda Ridgeline ---
  {
    id: "veh-15",
    stockNo: "H1015",
    vin: "5FPYK3F16RB700615",
    year: 2026,
    make: "Honda",
    model: "Ridgeline",
    trim: "RTL-E",
    condition: "new",
    msrp: 46800,
    invoice: 43700,
    sellingPrice: 46800,
    daysOnLot: 4,
    status: "available",
    exteriorColor: "Sonic Gray Pearl",
    interiorColor: "Black Leather",
    mileage: 0,
    imageUrl: "",
  },
  {
    id: "veh-16",
    stockNo: "H1016",
    vin: "5FPYK3F18RB700616",
    year: 2026,
    make: "Honda",
    model: "Ridgeline",
    trim: "Black Edition",
    condition: "new",
    msrp: 49900,
    invoice: 46600,
    sellingPrice: 49900,
    daysOnLot: 7,
    status: "available",
    exteriorColor: "Crystal Black Pearl",
    interiorColor: "Black Leather",
    mileage: 0,
    imageUrl: "",
  },
  // --- New Honda extras ---
  {
    id: "veh-17",
    stockNo: "H1017",
    vin: "19XFL1H76RE200217",
    year: 2026,
    make: "Honda",
    model: "Civic",
    trim: "Si",
    condition: "new",
    msrp: 31000,
    invoice: 29000,
    sellingPrice: 31000,
    daysOnLot: 1,
    status: "in-transit",
    exteriorColor: "Aegean Blue Metallic",
    interiorColor: "Black Cloth",
    mileage: 0,
    imageUrl: "",
  },
  {
    id: "veh-18",
    stockNo: "H1018",
    vin: "2HKRW2H59RH400118",
    year: 2026,
    make: "Honda",
    model: "CR-V",
    trim: "EX",
    condition: "new",
    msrp: 36100,
    invoice: 33700,
    sellingPrice: 36100,
    daysOnLot: 10,
    status: "available",
    exteriorColor: "Platinum White Pearl",
    interiorColor: "Gray Cloth",
    mileage: 0,
    imageUrl: "",
  },
  // --- Sold New ---
  {
    id: "veh-19",
    stockNo: "H1019",
    vin: "1HGCY2F56RA300319",
    year: 2026,
    make: "Honda",
    model: "Accord",
    trim: "Sport",
    condition: "new",
    msrp: 33900,
    invoice: 31700,
    sellingPrice: 33400,
    daysOnLot: 30,
    status: "sold",
    exteriorColor: "Radiant Red Metallic",
    interiorColor: "Black Cloth",
    mileage: 0,
    imageUrl: "",
  },
  {
    id: "veh-20",
    stockNo: "H1020",
    vin: "2HKRW2H51RH400120",
    year: 2025,
    make: "Honda",
    model: "CR-V",
    trim: "Hybrid Sport Touring",
    condition: "new",
    msrp: 41950,
    invoice: 39200,
    sellingPrice: 41200,
    daysOnLot: 60,
    status: "sold",
    exteriorColor: "Canyon River Blue Metallic",
    interiorColor: "Black Leather",
    mileage: 0,
    imageUrl: "",
  },
  // --- Used Vehicles (Trade-ins / Pre-owned) ---
  {
    id: "veh-21",
    stockNo: "U2001",
    vin: "1HGCV1F31LA800021",
    year: 2020,
    make: "Honda",
    model: "Accord",
    trim: "Sport 1.5T",
    condition: "used",
    msrp: 0,
    invoice: null,
    sellingPrice: 22995,
    daysOnLot: 15,
    status: "available",
    exteriorColor: "Modern Steel Metallic",
    interiorColor: "Black Cloth",
    mileage: 38420,
    imageUrl: "",
  },
  {
    id: "veh-22",
    stockNo: "U2002",
    vin: "5TDYK3DC8LS900022",
    year: 2020,
    make: "Toyota",
    model: "Highlander",
    trim: "XLE AWD",
    condition: "used",
    msrp: 0,
    invoice: null,
    sellingPrice: 31495,
    daysOnLot: 21,
    status: "available",
    exteriorColor: "Blizzard Pearl",
    interiorColor: "Harvest Beige",
    mileage: 42150,
    imageUrl: "",
  },
  {
    id: "veh-23",
    stockNo: "U2003",
    vin: "JTDKN3DU5A1100023",
    year: 2022,
    make: "Toyota",
    model: "Camry",
    trim: "SE",
    condition: "used",
    msrp: 0,
    invoice: null,
    sellingPrice: 23990,
    daysOnLot: 28,
    status: "available",
    exteriorColor: "Midnight Black Metallic",
    interiorColor: "Black Cloth",
    mileage: 29800,
    imageUrl: "",
  },
  {
    id: "veh-24",
    stockNo: "U2004",
    vin: "2HKRW2H74MH200024",
    year: 2021,
    make: "Honda",
    model: "CR-V",
    trim: "EX AWD",
    condition: "used",
    msrp: 0,
    invoice: null,
    sellingPrice: 26450,
    daysOnLot: 10,
    status: "available",
    exteriorColor: "Lunar Silver Metallic",
    interiorColor: "Gray Cloth",
    mileage: 34200,
    imageUrl: "",
  },
  {
    id: "veh-25",
    stockNo: "U2005",
    vin: "1N4BL4BV9LC300025",
    year: 2020,
    make: "Nissan",
    model: "Altima",
    trim: "2.5 SV",
    condition: "used",
    msrp: 0,
    invoice: null,
    sellingPrice: 18750,
    daysOnLot: 35,
    status: "available",
    exteriorColor: "Gun Metallic",
    interiorColor: "Charcoal Cloth",
    mileage: 51300,
    imageUrl: "",
  },
  {
    id: "veh-26",
    stockNo: "U2006",
    vin: "3CZRU5H38PM400026",
    year: 2023,
    make: "Honda",
    model: "HR-V",
    trim: "EX-L",
    condition: "used",
    msrp: 0,
    invoice: null,
    sellingPrice: 27200,
    daysOnLot: 7,
    status: "available",
    exteriorColor: "Nordic Forest Pearl",
    interiorColor: "Black Leather",
    mileage: 18650,
    imageUrl: "",
  },
  {
    id: "veh-27",
    stockNo: "U2007",
    vin: "1FTEW1E57KF500027",
    year: 2019,
    make: "Ford",
    model: "F-150",
    trim: "XLT SuperCrew 4x4",
    condition: "used",
    msrp: 0,
    invoice: null,
    sellingPrice: 33990,
    daysOnLot: 19,
    status: "available",
    exteriorColor: "Agate Black",
    interiorColor: "Medium Earth Gray",
    mileage: 47800,
    imageUrl: "",
  },
  {
    id: "veh-28",
    stockNo: "U2008",
    vin: "5YFBURHE1HP600028",
    year: 2023,
    make: "Toyota",
    model: "Corolla",
    trim: "LE",
    condition: "used",
    msrp: 0,
    invoice: null,
    sellingPrice: 20500,
    daysOnLot: 13,
    status: "available",
    exteriorColor: "Classic Silver Metallic",
    interiorColor: "Light Gray Cloth",
    mileage: 22100,
    imageUrl: "",
  },
  {
    id: "veh-29",
    stockNo: "U2009",
    vin: "19XFC2F69KE700029",
    year: 2019,
    make: "Honda",
    model: "Civic",
    trim: "EX Hatchback",
    condition: "used",
    msrp: 0,
    invoice: null,
    sellingPrice: 19450,
    daysOnLot: 42,
    status: "available",
    exteriorColor: "Aegean Blue Metallic",
    interiorColor: "Black Cloth",
    mileage: 55200,
    imageUrl: "",
  },
  {
    id: "veh-30",
    stockNo: "U2010",
    vin: "JN8AT2MT1LW800030",
    year: 2020,
    make: "Nissan",
    model: "Rogue",
    trim: "SL AWD",
    condition: "used",
    msrp: 0,
    invoice: null,
    sellingPrice: 22100,
    daysOnLot: 25,
    status: "available",
    exteriorColor: "Pearl White Tricoat",
    interiorColor: "Charcoal Leather",
    mileage: 43750,
    imageUrl: "",
  },
];
