export type Lead = {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  source:
    | "website"
    | "cars.com"
    | "autotrader"
    | "walk-in"
    | "phone"
    | "referral";
  status:
    | "new"
    | "contacted"
    | "qualified"
    | "appointment-set"
    | "shown"
    | "negotiating"
    | "sold"
    | "lost";
  aiScore: number;
  smartTags: string[];
  vehicleOfInterestId: string;
  assignedUserId: string;
  createdAt: string;
  lastActivityAt: string;
  lastActivityDescription: string;
};

export const leads: Lead[] = [
  {
    id: "lead-1",
    firstName: "Michael",
    lastName: "Torres",
    email: "m.torres88@gmail.com",
    phone: "(555) 312-8844",
    source: "website",
    status: "negotiating",
    aiScore: 92,
    smartTags: ["hot-lead", "trade-in", "returning-customer"],
    vehicleOfInterestId: "veh-1",
    assignedUserId: "user-1",
    createdAt: "2026-04-05T09:15:00Z",
    lastActivityAt: "2026-04-11T10:30:00Z",
    lastActivityDescription: "Submitted credit application online",
  },
  {
    id: "lead-2",
    firstName: "Jennifer",
    lastName: "Martinez",
    email: "jen.martinez@outlook.com",
    phone: "(555) 445-2290",
    source: "cars.com",
    status: "appointment-set",
    aiScore: 85,
    smartTags: ["hot-lead", "lease-expiring", "conquest"],
    vehicleOfInterestId: "veh-3",
    assignedUserId: "user-2",
    createdAt: "2026-04-07T14:22:00Z",
    lastActivityAt: "2026-04-10T16:45:00Z",
    lastActivityDescription: "Appointment confirmed for Saturday 11 AM",
  },
  {
    id: "lead-3",
    firstName: "Robert",
    lastName: "Anderson",
    email: "r.anderson@yahoo.com",
    phone: "(555) 778-1165",
    source: "walk-in",
    status: "shown",
    aiScore: 78,
    smartTags: ["trade-in", "weekend-buyer"],
    vehicleOfInterestId: "veh-12",
    assignedUserId: "user-1",
    createdAt: "2026-04-09T11:00:00Z",
    lastActivityAt: "2026-04-10T14:20:00Z",
    lastActivityDescription: "Test drove Pilot Touring, liked it",
  },
  {
    id: "lead-4",
    firstName: "Amanda",
    lastName: "Foster",
    email: "afoster22@gmail.com",
    phone: "(555) 663-9917",
    source: "autotrader",
    status: "qualified",
    aiScore: 71,
    smartTags: ["first-time-buyer", "credit-concern"],
    vehicleOfInterestId: "veh-4",
    assignedUserId: "user-2",
    createdAt: "2026-04-08T08:30:00Z",
    lastActivityAt: "2026-04-10T11:15:00Z",
    lastActivityDescription: "AI qualified — budget $350/mo, looking at Civic Sport",
  },
  {
    id: "lead-5",
    firstName: "David",
    lastName: "Thompson",
    email: "dthompson.work@gmail.com",
    phone: "(555) 224-5578",
    source: "referral",
    status: "sold",
    aiScore: 95,
    smartTags: ["returning-customer", "cash-buyer"],
    vehicleOfInterestId: "veh-19",
    assignedUserId: "user-1",
    createdAt: "2026-04-04T10:00:00Z",
    lastActivityAt: "2026-04-09T15:30:00Z",
    lastActivityDescription: "Took delivery of 2026 Accord Sport",
  },
  {
    id: "lead-6",
    firstName: "Priya",
    lastName: "Sharma",
    email: "priya.s@gmail.com",
    phone: "(555) 889-3312",
    source: "website",
    status: "new",
    aiScore: 62,
    smartTags: ["conquest"],
    vehicleOfInterestId: "veh-7",
    assignedUserId: "user-2",
    createdAt: "2026-04-11T07:45:00Z",
    lastActivityAt: "2026-04-11T07:45:00Z",
    lastActivityDescription: "Submitted lead form for Accord Sport Hybrid",
  },
  {
    id: "lead-7",
    firstName: "Kevin",
    lastName: "O'Brien",
    email: "kobrien55@hotmail.com",
    phone: "(555) 112-7743",
    source: "phone",
    status: "contacted",
    aiScore: 58,
    smartTags: ["trade-in"],
    vehicleOfInterestId: "veh-15",
    assignedUserId: "user-1",
    createdAt: "2026-04-09T16:30:00Z",
    lastActivityAt: "2026-04-10T09:00:00Z",
    lastActivityDescription: "Left voicemail, texted inventory link",
  },
  {
    id: "lead-8",
    firstName: "Lisa",
    lastName: "Nguyen",
    email: "lisa.nguyen.tx@gmail.com",
    phone: "(555) 446-8821",
    source: "website",
    status: "appointment-set",
    aiScore: 88,
    smartTags: ["hot-lead", "lease-expiring"],
    vehicleOfInterestId: "veh-10",
    assignedUserId: "user-2",
    createdAt: "2026-04-06T13:10:00Z",
    lastActivityAt: "2026-04-10T18:00:00Z",
    lastActivityDescription: "Confirmed test drive appointment for Sunday",
  },
  {
    id: "lead-9",
    firstName: "Marcus",
    lastName: "Green",
    email: "mgreen91@gmail.com",
    phone: "(555) 334-0098",
    source: "cars.com",
    status: "lost",
    aiScore: 35,
    smartTags: ["conquest"],
    vehicleOfInterestId: "veh-5",
    assignedUserId: "user-1",
    createdAt: "2026-04-04T11:20:00Z",
    lastActivityAt: "2026-04-08T10:00:00Z",
    lastActivityDescription: "No response after 3 follow-ups — marked lost",
  },
  {
    id: "lead-10",
    firstName: "Stephanie",
    lastName: "Reed",
    email: "steph.reed@icloud.com",
    phone: "(555) 556-2234",
    source: "walk-in",
    status: "negotiating",
    aiScore: 90,
    smartTags: ["hot-lead", "trade-in", "weekend-buyer"],
    vehicleOfInterestId: "veh-8",
    assignedUserId: "user-1",
    createdAt: "2026-04-08T10:45:00Z",
    lastActivityAt: "2026-04-11T09:00:00Z",
    lastActivityDescription: "Working numbers on Accord Touring Hybrid, trade 2021 Camry",
  },
  {
    id: "lead-11",
    firstName: "Brian",
    lastName: "Wallace",
    email: "bwallace@protonmail.com",
    phone: "(555) 778-4409",
    source: "autotrader",
    status: "new",
    aiScore: 55,
    smartTags: ["first-time-buyer"],
    vehicleOfInterestId: "veh-11",
    assignedUserId: "user-2",
    createdAt: "2026-04-11T06:30:00Z",
    lastActivityAt: "2026-04-11T06:30:00Z",
    lastActivityDescription: "AutoTrader lead — HR-V Sport inquiry",
  },
  {
    id: "lead-12",
    firstName: "Michelle",
    lastName: "Davis",
    email: "michelle.d@gmail.com",
    phone: "(555) 990-1123",
    source: "referral",
    status: "qualified",
    aiScore: 82,
    smartTags: ["returning-customer", "trade-in"],
    vehicleOfInterestId: "veh-13",
    assignedUserId: "user-1",
    createdAt: "2026-04-07T09:00:00Z",
    lastActivityAt: "2026-04-10T13:30:00Z",
    lastActivityDescription: "Referred by David Thompson, interested in Pilot TrailSport",
  },
  {
    id: "lead-13",
    firstName: "Carlos",
    lastName: "Ramirez",
    email: "carlos.r@outlook.com",
    phone: "(555) 667-3388",
    source: "website",
    status: "contacted",
    aiScore: 60,
    smartTags: ["credit-concern", "first-time-buyer"],
    vehicleOfInterestId: "veh-6",
    assignedUserId: "user-2",
    createdAt: "2026-04-09T20:15:00Z",
    lastActivityAt: "2026-04-10T10:30:00Z",
    lastActivityDescription: "AI chatted, customer concerned about credit approval",
  },
  {
    id: "lead-14",
    firstName: "Heather",
    lastName: "Mitchell",
    email: "h.mitchell@gmail.com",
    phone: "(555) 223-8801",
    source: "phone",
    status: "appointment-set",
    aiScore: 76,
    smartTags: ["trade-in", "weekend-buyer"],
    vehicleOfInterestId: "veh-2",
    assignedUserId: "user-1",
    createdAt: "2026-04-08T15:45:00Z",
    lastActivityAt: "2026-04-10T17:00:00Z",
    lastActivityDescription: "Wants to see CR-V Sport, appt Saturday 2 PM",
  },
  {
    id: "lead-15",
    firstName: "Tyler",
    lastName: "Brooks",
    email: "tbrooks@gmail.com",
    phone: "(555) 443-9977",
    source: "cars.com",
    status: "shown",
    aiScore: 80,
    smartTags: ["hot-lead", "trade-in"],
    vehicleOfInterestId: "veh-16",
    assignedUserId: "user-1",
    createdAt: "2026-04-06T08:00:00Z",
    lastActivityAt: "2026-04-10T15:45:00Z",
    lastActivityDescription: "Test drove Ridgeline Black Edition, comparing to Tacoma",
  },
  {
    id: "lead-16",
    firstName: "Emily",
    lastName: "Watson",
    email: "emily.watson@yahoo.com",
    phone: "(555) 118-6643",
    source: "website",
    status: "sold",
    aiScore: 97,
    smartTags: ["returning-customer", "lease-expiring"],
    vehicleOfInterestId: "veh-20",
    assignedUserId: "user-1",
    createdAt: "2026-04-04T07:30:00Z",
    lastActivityAt: "2026-04-07T16:00:00Z",
    lastActivityDescription: "Lease return + new CR-V Hybrid Sport Touring delivered",
  },
  {
    id: "lead-17",
    firstName: "Jason",
    lastName: "Park",
    email: "jpark.auto@gmail.com",
    phone: "(555) 332-5501",
    source: "autotrader",
    status: "contacted",
    aiScore: 48,
    smartTags: ["conquest"],
    vehicleOfInterestId: "veh-9",
    assignedUserId: "user-2",
    createdAt: "2026-04-10T12:00:00Z",
    lastActivityAt: "2026-04-10T14:30:00Z",
    lastActivityDescription: "AI sent vehicle specs and pricing via text",
  },
  {
    id: "lead-18",
    firstName: "Rachel",
    lastName: "Cooper",
    email: "rachel.cooper@gmail.com",
    phone: "(555) 887-2244",
    source: "walk-in",
    status: "qualified",
    aiScore: 74,
    smartTags: ["cash-buyer"],
    vehicleOfInterestId: "veh-24",
    assignedUserId: "user-1",
    createdAt: "2026-04-10T09:30:00Z",
    lastActivityAt: "2026-04-10T11:45:00Z",
    lastActivityDescription: "Walk-in, looking at used CR-V EX, paying cash",
  },
  {
    id: "lead-19",
    firstName: "Nathan",
    lastName: "Hughes",
    email: "nhughes@outlook.com",
    phone: "(555) 665-9900",
    source: "website",
    status: "new",
    aiScore: 44,
    smartTags: ["first-time-buyer"],
    vehicleOfInterestId: "veh-17",
    assignedUserId: "user-2",
    createdAt: "2026-04-11T08:15:00Z",
    lastActivityAt: "2026-04-11T08:15:00Z",
    lastActivityDescription: "Inquiry on incoming Civic Si",
  },
  {
    id: "lead-20",
    firstName: "Angela",
    lastName: "Price",
    email: "angela.price@gmail.com",
    phone: "(555) 554-1188",
    source: "referral",
    status: "appointment-set",
    aiScore: 86,
    smartTags: ["hot-lead", "returning-customer", "trade-in"],
    vehicleOfInterestId: "veh-14",
    assignedUserId: "user-1",
    createdAt: "2026-04-07T16:00:00Z",
    lastActivityAt: "2026-04-10T19:00:00Z",
    lastActivityDescription: "Referred by sister, wants Pilot EX-L, appt Monday 10 AM",
  },
];
